-- =====================================================================
-- SUPERSEDED — see migrations_payment_ledger_v2.sql
--
-- This file modelled per-workout charges settling independently, which
-- created a visible asymmetry (a no-show fee could appear days before the
-- matching coach earning was known). The second interview pass replaced it
-- with one proportional charge per trainee per week. v2's PART 0 already
-- drops the tables/functions this file created, so running v2 alone is
-- sufficient — this file is kept only for the historical record of why the
-- model changed, and should not be run.
-- =====================================================================
